<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.11" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1"/>
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="RestSharp" Version="113.0.0" />
        <PackageReference Include="xunit" Version="2.9.2"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Teachio.BLL\Teachio.BLL.csproj" />
      <ProjectReference Include="..\Teachio.DAL\Teachio.DAL.csproj" />
      <ProjectReference Include="..\Teachio.WebApi\Teachio.WebApi.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Utils\BeforeAndAfterAttributes\Courses\Sections\" />
      <Folder Include="Utils\BeforeAndAfterAttributes\Courses\Videos\VideoProgress\" />
      <Folder Include="Utils\BeforeAndAfterAttributes\Courses\Videos\Videos\" />
      <Folder Include="Utils\BeforeAndAfterAttributes\Users\" />
    </ItemGroup>

    <ItemGroup>
      <None Update="TestData\AppUser.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Course.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Section.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Video.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="TestData\VideoProgress.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
