apiVersion: v1
kind: Secret
metadata:
  name: teachio-api-secrets
  namespace: teachio
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=teachio-sql,1433;Database=teachio-db;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True;"
