<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="MediatR\Courses\Videos\Videos\UploadVideo\" />
      <Folder Include="MediatR\Users\" />
      <Folder Include="Utils\Attributes\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.1.1" />
      <PackageReference Include="FluentResults" Version="4.0.0" />
      <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
      <PackageReference Include="MediatR" Version="13.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
      <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.10" />
      <PackageReference Include="MimeKit" Version="4.15.1" />
      <PackageReference Include="Serilog" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Teachio.DAL\Teachio.DAL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\SharedResource\CannotFindSharedResource.en.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>CannotFindSharedResource.en.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\SharedResource\CannotMapSharedResource.en.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>FailedToMapSharedResource.en.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\SharedResource\AlreadyExistsSharedResource.en.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>AlreadyExistsSharedResource.en.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\SharedResource\NoPermissionsSharedResource.en.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>NoPermissionsSharedResource.en.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\SharedResource\CannotFindSharedResource.en.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>CannotFindSharedResource.en.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\SharedResource\CannotMapSharedResource.en.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>CannotMapSharedResource.en.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\SharedResource\AlreadyExistsSharedResource.en.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>AlreadyExistsSharedResource.en.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\SharedResource\NoPermissionsSharedResource.en.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>NoPermissionsSharedResource.en.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
