//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teachio.BLL.Resources.SharedResource {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuthSharedResource_en {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthSharedResource_en() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teachio.BLL.Resources.SharedResource.AuthSharedResource.en", typeof(AuthSharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect.
        /// </summary>
        internal static string CurrentPasswordInvalid {
            get {
                return ResourceManager.GetString("CurrentPasswordInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to change password.
        /// </summary>
        internal static string PasswordChangeFailed {
            get {
                return ResourceManager.GetString("PasswordChangeFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current and new passwords must be provided to change password.
        /// </summary>
        internal static string PasswordChangeRequiresBoth {
            get {
                return ResourceManager.GetString("PasswordChangeRequiresBoth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh token has expired.
        /// </summary>
        internal static string RefreshTokenExpired {
            get {
                return ResourceManager.GetString("RefreshTokenExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh token is invalid.
        /// </summary>
        internal static string RefreshTokenInvalid {
            get {
                return ResourceManager.GetString("RefreshTokenInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh token is missing.
        /// </summary>
        internal static string RefreshTokenMissing {
            get {
                return ResourceManager.GetString("RefreshTokenMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh token has been revoked.
        /// </summary>
        internal static string RefreshTokenRevoked {
            get {
                return ResourceManager.GetString("RefreshTokenRevoked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to issue authentication tokens.
        /// </summary>
        internal static string TokenIssueFailed {
            get {
                return ResourceManager.GetString("TokenIssueFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to delete user.
        /// </summary>
        internal static string UserDeleteFailed {
            get {
                return ResourceManager.GetString("UserDeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to register user.
        /// </summary>
        internal static string UserRegistrationFailed {
            get {
                return ResourceManager.GetString("UserRegistrationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration PIN has expired.
        /// </summary>
        internal static string RegistrationPinExpired {
            get {
                return ResourceManager.GetString("RegistrationPinExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration PIN is invalid.
        /// </summary>
        internal static string RegistrationPinInvalid {
            get {
                return ResourceManager.GetString("RegistrationPinInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration PIN request was not found.
        /// </summary>
        internal static string RegistrationPinNotFound {
            get {
                return ResourceManager.GetString("RegistrationPinNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please wait before requesting a new PIN.
        /// </summary>
        internal static string RegistrationPinResendTooSoon {
            get {
                return ResourceManager.GetString("RegistrationPinResendTooSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to send registration PIN email.
        /// </summary>
        internal static string RegistrationPinSendFailed {
            get {
                return ResourceManager.GetString("RegistrationPinSendFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to update user.
        /// </summary>
        internal static string UserUpdateFailed {
            get {
                return ResourceManager.GetString("UserUpdateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User with email '{0}' already exists.
        /// </summary>
        internal static string UserWithEmailAlreadyExists {
            get {
                return ResourceManager.GetString("UserWithEmailAlreadyExists", resourceCulture);
            }
        }
    }
}
