//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teachio.BLL.Resources.SharedResource {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AvatarMetadataSharedResource_en {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AvatarMetadataSharedResource_en() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teachio.BLL.Resources.SharedResource.AvatarMetadataSharedResource.en", typeof(AvatarMetadataSharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string AvatarFilePathIsEmpty {
            get {
                return ResourceManager.GetString("AvatarFilePathIsEmpty", resourceCulture);
            }
        }

        internal static string AvatarFileNotFound {
            get {
                return ResourceManager.GetString("AvatarFileNotFound", resourceCulture);
            }
        }

        internal static string AvatarFormatNotSupported {
            get {
                return ResourceManager.GetString("AvatarFormatNotSupported", resourceCulture);
            }
        }

        internal static string AvatarResolutionInvalid {
            get {
                return ResourceManager.GetString("AvatarResolutionInvalid", resourceCulture);
            }
        }

        internal static string AvatarResolutionOutOfRange {
            get {
                return ResourceManager.GetString("AvatarResolutionOutOfRange", resourceCulture);
            }
        }

        internal static string AvatarAspectRatioInvalid {
            get {
                return ResourceManager.GetString("AvatarAspectRatioInvalid", resourceCulture);
            }
        }

        internal static string AvatarResolutionTooLong {
            get {
                return ResourceManager.GetString("AvatarResolutionTooLong", resourceCulture);
            }
        }

        internal static string UnsupportedContentType {
            get {
                return ResourceManager.GetString("UnsupportedContentType", resourceCulture);
            }
        }

        internal static string ContentTypeExtensionCannotResolve {
            get {
                return ResourceManager.GetString("ContentTypeExtensionCannotResolve", resourceCulture);
            }
        }

        internal static string AvatarMetadataProcessingFailed {
            get {
                return ResourceManager.GetString("AvatarMetadataProcessingFailed", resourceCulture);
            }
        }
    }
}
