//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teachio.BLL.Resources.SharedResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CannotFindSharedResource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CannotFindSharedResource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teachio.BLL.Resources.SharedResource.CannotFindSharedResource.en", typeof(CannotFindSharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no course with such Id: {0}.
        /// </summary>
        internal static string CannotFindCourseById {
            get {
                return ResourceManager.GetString("CannotFindCourseById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no course with key &apos;{1}&apos;: {0}.
        /// </summary>
        internal static string CannotFindCourseByKey {
            get {
                return ResourceManager.GetString("CannotFindCourseByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no section with such Id: {0}.
        /// </summary>
        internal static string CannotFindSectionById {
            get {
                return ResourceManager.GetString("CannotFindSectionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no section with key &apos;{1}&apos;: {0}.
        /// </summary>
        internal static string CannotFindSectionByKey {
            get {
                return ResourceManager.GetString("CannotFindSectionByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with such Id: {0}.
        /// </summary>
        internal static string CannotFindUserById {
            get {
                return ResourceManager.GetString("CannotFindUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with key &apos;{1}&apos;: {0}.
        /// </summary>
        internal static string CannotFindUserByKey {
            get {
                return ResourceManager.GetString("CannotFindUserByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no video with such Id: {0}.
        /// </summary>
        internal static string CannotFindVideoById {
            get {
                return ResourceManager.GetString("CannotFindVideoById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no video with key &apos;{1}&apos;: {0}.
        /// </summary>
        internal static string CannotFindVideoByKey {
            get {
                return ResourceManager.GetString("CannotFindVideoByKey", resourceCulture);
            }
        }
    }
}
