//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teachio.BLL.Resources.SharedResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NoPermissionsSharedResource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NoPermissionsSharedResource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teachio.BLL.Resources.SharedResource.NoPermissionsSharedResource.en", typeof(NoPermissionsSharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have any permission to create section for the course of another user.
        /// </summary>
        internal static string NoPermissionsToCreateSectionForCourseOfAnotherUser {
            get {
                return ResourceManager.GetString("NoPermissionsToCreateSectionForCourseOfAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{1}&apos; doesn&apos;t have any permission to create section for the course with Id {0} of another user with Id &apos;{2}&apos;.
        /// </summary>
        internal static string NoPermissionsToCreateSectionForCourseOfAnotherUserWithId {
            get {
                return ResourceManager.GetString("NoPermissionsToCreateSectionForCourseOfAnotherUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have any permission to create video for the section of another user&apos;s course.
        /// </summary>
        internal static string NoPermissionsToCreateVideoForSectionOfCourseOfAnotherUser {
            get {
                return ResourceManager.GetString("NoPermissionsToCreateVideoForSectionOfCourseOfAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{2}&apos; doesn&apos;t have any permission to create video for the section with Id &apos;{0}&apos; of course with Id &apos;{1}&apos; of another user with Id &apos;{3}&apos;.
        /// </summary>
        internal static string NoPermissionsToCreateVideoForSectionOfCourseOfAnotherUserWithId {
            get {
                return ResourceManager.GetString("NoPermissionsToCreateVideoForSectionOfCourseOfAnotherUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have any permission to delete course with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToDeleteCourseForUser {
            get {
                return ResourceManager.GetString("NoPermissionsToDeleteCourseForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{1}&apos; doesn&apos;t have any permission to delete course with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToDeleteCourseForUserWithId {
            get {
                return ResourceManager.GetString("NoPermissionsToDeleteCourseForUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have any permission to delete section with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToDeleteSectionForUser {
            get {
                return ResourceManager.GetString("NoPermissionsToDeleteSectionForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{1}&apos; doesn&apos;t have any permission to delete section with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToDeleteSectionForUserWithId {
            get {
                return ResourceManager.GetString("NoPermissionsToDeleteSectionForUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have any permission to delete video with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToDeleteVideoForUser {
            get {
                return ResourceManager.GetString("NoPermissionsToDeleteVideoForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{1}&apos; doesn&apos;t have any permission to delete video with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToDeleteVideoForUserWithId {
            get {
                return ResourceManager.GetString("NoPermissionsToDeleteVideoForUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have any permission to update course with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToUpdateCourseForUser {
            get {
                return ResourceManager.GetString("NoPermissionsToUpdateCourseForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{1}&apos; doesn&apos;t have any permission to update course with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToUpdateCourseForUserWithId {
            get {
                return ResourceManager.GetString("NoPermissionsToUpdateCourseForUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have any permission to update section with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToUpdateSectionForUser {
            get {
                return ResourceManager.GetString("NoPermissionsToUpdateSectionForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{1}&apos; doesn&apos;t have any permission to update section with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToUpdateSectionForUserWithId {
            get {
                return ResourceManager.GetString("NoPermissionsToUpdateSectionForUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have any permission to update video with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToUpdateVideoForUser {
            get {
                return ResourceManager.GetString("NoPermissionsToUpdateVideoForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{1}&apos; doesn&apos;t have any permission to update video with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToUpdateVideoForUserWithId {
            get {
                return ResourceManager.GetString("NoPermissionsToUpdateVideoForUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have any permission to update video progress with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToUpdateVideoProgressForUser {
            get {
                return ResourceManager.GetString("NoPermissionsToUpdateVideoProgressForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{1}&apos; doesn&apos;t have any permission to update video progress with Id &apos;{0}&apos;.
        /// </summary>
        internal static string NoPermissionsToUpdateVideoProgressForUserWithId {
            get {
                return ResourceManager.GetString("NoPermissionsToUpdateVideoProgressForUserWithId", resourceCulture);
            }
        }
    }
}
