//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teachio.BLL.Resources.SharedResource {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VideoMetadataSharedResource_en {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VideoMetadataSharedResource_en() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teachio.BLL.Resources.SharedResource.VideoMetadataSharedResource.en", typeof(VideoMetadataSharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve file extension for content type '{0}'.
        /// </summary>
        internal static string ContentTypeExtensionCannotResolve {
            get {
                return ResourceManager.GetString("ContentTypeExtensionCannotResolve", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFprobe analysis timed out after {0} seconds.
        /// </summary>
        internal static string FfprobeAnalysisTimedOut {
            get {
                return ResourceManager.GetString("FfprobeAnalysisTimedOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFprobe executable path is not configured.
        /// </summary>
        internal static string FfprobeExecutablePathNotConfigured {
            get {
                return ResourceManager.GetString("FfprobeExecutablePathNotConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFprobe failed with exit code {0}.
        /// </summary>
        internal static string FfprobeFailedWithExitCode {
            get {
                return ResourceManager.GetString("FfprobeFailedWithExitCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFprobe output did not contain format information.
        /// </summary>
        internal static string FfprobeOutputMissingFormat {
            get {
                return ResourceManager.GetString("FfprobeOutputMissingFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFprobe output did not contain video stream resolution information.
        /// </summary>
        internal static string FfprobeOutputMissingResolution {
            get {
                return ResourceManager.GetString("FfprobeOutputMissingResolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFprobe output did not contain valid duration information.
        /// </summary>
        internal static string FfprobeOutputInvalidDuration {
            get {
                return ResourceManager.GetString("FfprobeOutputInvalidDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to parse FFprobe output.
        /// </summary>
        internal static string FfprobeOutputParseFailed {
            get {
                return ResourceManager.GetString("FfprobeOutputParseFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFprobe process was not started.
        /// </summary>
        internal static string FfprobeProcessNotStarted {
            get {
                return ResourceManager.GetString("FfprobeProcessNotStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFprobe returned empty output.
        /// </summary>
        internal static string FfprobeReturnedEmptyOutput {
            get {
                return ResourceManager.GetString("FfprobeReturnedEmptyOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFprobe returned invalid duration value.
        /// </summary>
        internal static string FfprobeInvalidDurationValue {
            get {
                return ResourceManager.GetString("FfprobeInvalidDurationValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to execute FFprobe for video metadata extraction.
        /// </summary>
        internal static string FfprobeExecutionFailed {
            get {
                return ResourceManager.GetString("FfprobeExecutionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FFprobe returned invalid video resolution information.
        /// </summary>
        internal static string InvalidVideoResolution {
            get {
                return ResourceManager.GetString("InvalidVideoResolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported content type '{0}'. Allowed values: {1}.
        /// </summary>
        internal static string UnsupportedContentType {
            get {
                return ResourceManager.GetString("UnsupportedContentType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported video format. Allowed formats: {0}.
        /// </summary>
        internal static string UnsupportedVideoFormat {
            get {
                return ResourceManager.GetString("UnsupportedVideoFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported video resolution '{0}p'. Allowed resolutions: {1}.
        /// </summary>
        internal static string UnsupportedVideoResolution {
            get {
                return ResourceManager.GetString("UnsupportedVideoResolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Video duration exceeds the maximum allowed value of {0} seconds.
        /// </summary>
        internal static string VideoDurationExceedsLimit {
            get {
                return ResourceManager.GetString("VideoDurationExceedsLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Video file path cannot be null or whitespace.
        /// </summary>
        internal static string VideoFilePathIsEmpty {
            get {
                return ResourceManager.GetString("VideoFilePathIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Video file was not found at '{0}'.
        /// </summary>
        internal static string VideoFileNotFound {
            get {
                return ResourceManager.GetString("VideoFileNotFound", resourceCulture);
            }
        }
    }
}
