// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Studi.DAL.Persistence;

#nullable disable

namespace Studi.DAL.Persistence.Migrations
{
    [DbContext(typeof(StudiDbContext))]
    [Migration("20260511193758_AddAppUserRegexChecks")]
    partial class AddAppUserRegexChecks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SectionsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("WatchingUsersCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Courses", "courses", t =>
                        {
                            t.HasCheckConstraint("CK_Course_CourseName_Regex", "[CourseName] NOT LIKE '%[^A-Za-z0-9,!?-]%'");

                            t.HasCheckConstraint("CK_Course_Description_Regex", "[Description] NOT LIKE '%[^A-Za-z0-9 ,.!?%$#\"'':&()+=*/-–]%'");

                            t.HasCheckConstraint("CK_Course_SectionsCount_Range", "[SectionsCount] >= 0 AND [SectionsCount] <= 35");

                            t.HasCheckConstraint("CK_Course_Title_Regex", "[Title] NOT LIKE '%[^A-Za-z0-9 ,!?-]%'");

                            t.HasCheckConstraint("CK_Course_WatchingUsersCount_NonNegative", "[WatchingUsersCount] >= 0");
                        });
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Sections.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("VideosCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("Sections", "courses", t =>
                        {
                            t.HasCheckConstraint("CK_Section_OrderIndex_Range", "[OrderIndex] >= 0 AND [OrderIndex] <= 34");

                            t.HasCheckConstraint("CK_Section_SectionName_Regex", "[SectionName] NOT LIKE '%[^A-Za-z0-9,!?-]%'");

                            t.HasCheckConstraint("CK_Section_Title_Regex", "[Title] NOT LIKE '%[^A-Za-z0-9 ,!?-]%'");

                            t.HasCheckConstraint("CK_Section_VideosCount_Range", "[VideosCount] >= 0 AND [VideosCount] <= 40");
                        });
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.ThumbnailFiles.ThumbnailFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ThumbnailName")
                        .IsRequired()
                        .HasMaxLength(110)
                        .HasColumnType("nvarchar(110)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("ThumbnailFiles", "courses", t =>
                        {
                            t.HasCheckConstraint("CK_ThumbnailFile_ContentType_AllowedValues", "[ContentType] IN ('image/jpeg', 'image/png')");

                            t.HasCheckConstraint("CK_ThumbnailFile_Resolution_AspectRatioRange", "CHARINDEX('x', [Resolution]) > 1 AND CHARINDEX('x', [Resolution]) < LEN([Resolution]) AND CHARINDEX('x', [Resolution], CHARINDEX('x', [Resolution]) + 1) = 0 AND TRY_CONVERT(int, LEFT([Resolution], CHARINDEX('x', [Resolution]) - 1)) IS NOT NULL AND TRY_CONVERT(int, SUBSTRING([Resolution], CHARINDEX('x', [Resolution]) + 1, LEN([Resolution]))) IS NOT NULL AND TRY_CONVERT(int, LEFT([Resolution], CHARINDEX('x', [Resolution]) - 1)) >= 1280 AND TRY_CONVERT(int, LEFT([Resolution], CHARINDEX('x', [Resolution]) - 1)) <= 2560 AND TRY_CONVERT(int, SUBSTRING([Resolution], CHARINDEX('x', [Resolution]) + 1, LEN([Resolution]))) >= 720 AND TRY_CONVERT(int, SUBSTRING([Resolution], CHARINDEX('x', [Resolution]) + 1, LEN([Resolution]))) <= 1440 AND TRY_CONVERT(int, LEFT([Resolution], CHARINDEX('x', [Resolution]) - 1)) * 9 = TRY_CONVERT(int, SUBSTRING([Resolution], CHARINDEX('x', [Resolution]) + 1, LEN([Resolution]))) * 16");

                            t.HasCheckConstraint("CK_ThumbnailFile_ThumbnailName_Regex", "[ThumbnailName] NOT LIKE '%[^A-Za-z0-9.,!?-]%'");
                        });
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Videos.VideoFiles.VideoFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Resolution")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoName")
                        .IsRequired()
                        .HasMaxLength(110)
                        .HasColumnType("nvarchar(110)");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("VideoFiles", "courses", t =>
                        {
                            t.HasCheckConstraint("CK_VideoFile_ContentType_AllowedValues", "[ContentType] IN ('video/mp4', 'video/quicktime')");

                            t.HasCheckConstraint("CK_VideoFile_DurationSeconds_Range", "[DurationSeconds] >= 0 AND [DurationSeconds] <= 3600");

                            t.HasCheckConstraint("CK_VideoFile_Resolution_AllowedValues", "[Resolution] IN (480, 720, 1080, 1440)");

                            t.HasCheckConstraint("CK_VideoFile_VideoName_Regex", "[VideoName] NOT LIKE '%[^A-Za-z0-9.,!?-]%'");
                        });
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Videos.VideoProgress.VideoProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PositionSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("VideoProgress", "courses", t =>
                        {
                            t.HasCheckConstraint("CK_VideoProgress_PositionSeconds_Range", "[PositionSeconds] >= 0 AND [PositionSeconds] <= 3600");
                        });
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Videos.Videos.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("Videos", "courses", t =>
                        {
                            t.HasCheckConstraint("CK_Video_OrderIndex_Range", "[OrderIndex] >= 0 AND [OrderIndex] <= 39");

                            t.HasCheckConstraint("CK_Video_Title_Regex", "[Title] NOT LIKE '%[^A-Za-z0-9 ,!?-]%'");
                        });
                });

            modelBuilder.Entity("Studi.DAL.Entities.Shared.UserCourse", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppUserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UserCourse", "courses");
                });

            modelBuilder.Entity("Studi.DAL.Entities.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AppUsers", "users", t =>
                        {
                            t.HasCheckConstraint("CK_AppUser_Name_Regex", "[Name] NOT LIKE '%[^A-Za-z'' ]%'");

                            t.HasCheckConstraint("CK_AppUser_Surname_Regex", "[Surname] NOT LIKE '%[^A-Za-z'' ]%'");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Studi.DAL.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Studi.DAL.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Studi.DAL.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Studi.DAL.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Courses.Course", b =>
                {
                    b.HasOne("Studi.DAL.Entities.Users.AppUser", "OwnerUser")
                        .WithMany("OwnedCourses")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Sections.Section", b =>
                {
                    b.HasOne("Studi.DAL.Entities.Courses.Courses.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.ThumbnailFiles.ThumbnailFile", b =>
                {
                    b.HasOne("Studi.DAL.Entities.Courses.Courses.Course", "Course")
                        .WithOne("ThumbnailFile")
                        .HasForeignKey("Studi.DAL.Entities.Courses.ThumbnailFiles.ThumbnailFile", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Videos.VideoFiles.VideoFile", b =>
                {
                    b.HasOne("Studi.DAL.Entities.Courses.Videos.Videos.Video", "Video")
                        .WithOne("VideoFile")
                        .HasForeignKey("Studi.DAL.Entities.Courses.Videos.VideoFiles.VideoFile", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Videos.VideoProgress.VideoProgress", b =>
                {
                    b.HasOne("Studi.DAL.Entities.Courses.Videos.Videos.Video", "Video")
                        .WithOne("VideoProgress")
                        .HasForeignKey("Studi.DAL.Entities.Courses.Videos.VideoProgress.VideoProgress", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Videos.Videos.Video", b =>
                {
                    b.HasOne("Studi.DAL.Entities.Courses.Sections.Section", "Section")
                        .WithMany("Videos")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Studi.DAL.Entities.Shared.UserCourse", b =>
                {
                    b.HasOne("Studi.DAL.Entities.Users.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Studi.DAL.Entities.Courses.Courses.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Courses.Course", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("ThumbnailFile");
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Sections.Section", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Studi.DAL.Entities.Courses.Videos.Videos.Video", b =>
                {
                    b.Navigation("VideoFile");

                    b.Navigation("VideoProgress")
                        .IsRequired();
                });

            modelBuilder.Entity("Studi.DAL.Entities.Users.AppUser", b =>
                {
                    b.Navigation("OwnedCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
