//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studi.BLL.Resources.SharedResource {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoogleDriveStorageSharedResource_en {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoogleDriveStorageSharedResource_en() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studi.BLL.Resources.SharedResource.GoogleDriveStorageSharedResource.en", typeof(GoogleDriveStorageSharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Content type cannot be null or whitespace.
        /// </summary>
        internal static string ContentTypeIsEmpty {
            get {
                return ResourceManager.GetString("ContentTypeIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive credentials are ambiguous. Configure only one source: OAuth credentials or service account credentials.
        /// </summary>
        internal static string CredentialsAmbiguous {
            get {
                return ResourceManager.GetString("CredentialsAmbiguous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive credentials are not configured. Set OAuthClientId/OAuthClientSecret/OAuthRefreshToken or ServiceAccountCredentialPath/ServiceAccountCredentialJson.
        /// </summary>
        internal static string CredentialsNotConfigured {
            get {
                return ResourceManager.GetString("CredentialsNotConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive did not return created folder identifier.
        /// </summary>
        internal static string CreatedFolderIdNotReturned {
            get {
                return ResourceManager.GetString("CreatedFolderIdNotReturned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to delete Google Drive file '{0}'.
        /// </summary>
        internal static string DeleteFileFailed {
            get {
                return ResourceManager.GetString("DeleteFileFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to delete Google Drive file '{0}' by path.
        /// </summary>
        internal static string DeleteFileByPathFailed {
            get {
                return ResourceManager.GetString("DeleteFileByPathFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File stream cannot be null.
        /// </summary>
        internal static string FileStreamIsNull {
            get {
                return ResourceManager.GetString("FileStreamIsNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File stream must be readable.
        /// </summary>
        internal static string FileStreamNotReadable {
            get {
                return ResourceManager.GetString("FileStreamNotReadable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive file identifier cannot be null or whitespace.
        /// </summary>
        internal static string FileIdentifierIsEmpty {
            get {
                return ResourceManager.GetString("FileIdentifierIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File name cannot be null or whitespace.
        /// </summary>
        internal static string FileNameIsEmpty {
            get {
                return ResourceManager.GetString("FileNameIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize Google Drive client.
        /// </summary>
        internal static string InitializeClientFailed {
            get {
                return ResourceManager.GetString("InitializeClientFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize Google Drive credentials.
        /// </summary>
        internal static string InitializeCredentialsFailed {
            get {
                return ResourceManager.GetString("InitializeCredentialsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple Google Drive files named '{0}' were found in the same folder.
        /// </summary>
        internal static string MultipleFilesWithSameName {
            get {
                return ResourceManager.GetString("MultipleFilesWithSameName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive file '{0}' was not found by path.
        /// </summary>
        internal static string FileNotFoundByPath {
            get {
                return ResourceManager.GetString("FileNotFoundByPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive download failed with status '{0}'.
        /// </summary>
        internal static string DownloadFailedWithStatus {
            get {
                return ResourceManager.GetString("DownloadFailedWithStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to download file from Google Drive.
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive OAuth credentials are incomplete. Set OAuthClientId, OAuthClientSecret and OAuthRefreshToken.
        /// </summary>
        internal static string OAuthCredentialsIncomplete {
            get {
                return ResourceManager.GetString("OAuthCredentialsIncomplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive root folder is not available.
        /// </summary>
        internal static string RootFolderIsNotAvailable {
            get {
                return ResourceManager.GetString("RootFolderIsNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive root folder is not configured. Set RootFolderName or RootFolderId.
        /// </summary>
        internal static string RootFolderNotConfigured {
            get {
                return ResourceManager.GetString("RootFolderNotConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive service account credentials are ambiguous. Configure only one source: ServiceAccountCredentialPath or ServiceAccountCredentialJson.
        /// </summary>
        internal static string ServiceAccountCredentialsAmbiguous {
            get {
                return ResourceManager.GetString("ServiceAccountCredentialsAmbiguous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive credential file was not found at '{0}'.
        /// </summary>
        internal static string ServiceAccountCredentialFileNotFound {
            get {
                return ResourceManager.GetString("ServiceAccountCredentialFileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to upload file to Google Drive.
        /// </summary>
        internal static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive upload failed with status '{0}'.
        /// </summary>
        internal static string UploadFailedWithStatus {
            get {
                return ResourceManager.GetString("UploadFailedWithStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive did not return uploaded file identifier.
        /// </summary>
        internal static string UploadedFileIdentifierNotReturned {
            get {
                return ResourceManager.GetString("UploadedFileIdentifierNotReturned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive folder name cannot be null or whitespace.
        /// </summary>
        internal static string FolderNameIsEmpty {
            get {
                return ResourceManager.GetString("FolderNameIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive folder '{0}' was not found by path.
        /// </summary>
        internal static string FolderNotFoundByPath {
            get {
                return ResourceManager.GetString("FolderNotFoundByPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Drive folder named '{0}' already exists in the target folder.
        /// </summary>
        internal static string FolderAlreadyExistsInParent {
            get {
                return ResourceManager.GetString("FolderAlreadyExistsInParent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to rename Google Drive folder '{0}'.
        /// </summary>
        internal static string RenameFolderFailed {
            get {
                return ResourceManager.GetString("RenameFolderFailed", resourceCulture);
            }
        }
    }
}
