//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studi.BLL.Resources.SharedResource {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ThumbnailMetadataSharedResource_en {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThumbnailMetadataSharedResource_en() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studi.BLL.Resources.SharedResource.ThumbnailMetadataSharedResource.en", typeof(ThumbnailMetadataSharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve file extension for content type '{0}'.
        /// </summary>
        internal static string ContentTypeExtensionCannotResolve {
            get {
                return ResourceManager.GetString("ContentTypeExtensionCannotResolve", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thumbnail aspect ratio must be {0}:{1}.
        /// </summary>
        internal static string ThumbnailAspectRatioInvalid {
            get {
                return ResourceManager.GetString("ThumbnailAspectRatioInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thumbnail file was not found at '{0}'.
        /// </summary>
        internal static string ThumbnailFileNotFound {
            get {
                return ResourceManager.GetString("ThumbnailFileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thumbnail file path cannot be null or whitespace.
        /// </summary>
        internal static string ThumbnailFilePathIsEmpty {
            get {
                return ResourceManager.GetString("ThumbnailFilePathIsEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported thumbnail format. Allowed formats: {0}.
        /// </summary>
        internal static string ThumbnailFormatNotSupported {
            get {
                return ResourceManager.GetString("ThumbnailFormatNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to read thumbnail metadata.
        /// </summary>
        internal static string ThumbnailMetadataProcessingFailed {
            get {
                return ResourceManager.GetString("ThumbnailMetadataProcessingFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thumbnail resolution information is invalid.
        /// </summary>
        internal static string ThumbnailResolutionInvalid {
            get {
                return ResourceManager.GetString("ThumbnailResolutionInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thumbnail resolution must be between {0}x{1} and {2}x{3}.
        /// </summary>
        internal static string ThumbnailResolutionOutOfRange {
            get {
                return ResourceManager.GetString("ThumbnailResolutionOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thumbnail resolution exceeds the maximum allowed length of {0} characters.
        /// </summary>
        internal static string ThumbnailResolutionTooLong {
            get {
                return ResourceManager.GetString("ThumbnailResolutionTooLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported content type '{0}'. Allowed values: {1}.
        /// </summary>
        internal static string UnsupportedContentType {
            get {
                return ResourceManager.GetString("UnsupportedContentType", resourceCulture);
            }
        }
    }
}
