//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studi.BLL.Resources.SharedResource {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VideoUploadSharedResource_en {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VideoUploadSharedResource_en() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studi.BLL.Resources.SharedResource.VideoUploadSharedResource.en", typeof(VideoUploadSharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generated video file name exceeds the maximum allowed length of {0} characters.
        /// </summary>
        internal static string GeneratedVideoFileNameTooLong {
            get {
                return ResourceManager.GetString("GeneratedVideoFileNameTooLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to process uploaded video file.
        /// </summary>
        internal static string UploadVideoProcessingFailed {
            get {
                return ResourceManager.GetString("UploadVideoProcessingFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to rollback uploaded Google Drive file with Id '{0}': {1}.
        /// </summary>
        internal static string UploadVideoRollbackFailed {
            get {
                return ResourceManager.GetString("UploadVideoRollbackFailed", resourceCulture);
            }
        }
    }
}
