name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore Teachio.sln -p:NuGetAudit=false

      - name: Build
        run: dotnet build Teachio.sln -c Release --no-restore -p:NuGetAudit=false

      - name: Test
        run: dotnet test Teachio.sln -c Release --no-build -p:NuGetAudit=false

      - name: Format Check
        run: dotnet format Teachio.sln --verify-no-changes --severity error --no-restore
